#
# Docker PostgreSQL offical image
# see: https://hub.docker.com/_/postgres/
#
FROM postgres:14.2-alpine
RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
ENV LANG ja_JP.utf8
